title: Juan Ignacio Caballero Garzón # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Image&signal data scientist. PhD student
  <br><br>
  Bachelor in Materials engineering 
  <br><br>
  <a href="https://www.linkedin.com/in/juan-ignacio-caballero-garz%C3%B3n-/">LinkedIn</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
